const adjectives = {
    'A': ['Adventurous', 'Amusing', 'Accident-waiting-to-happen', 'Artistic', 'Awesome', 'Athletic', 'Adorable', 'Ambitious', 'Always-late', 'Alert'],
    'B': ['Brave', 'Bright', 'Bubbly', 'Blissful', 'Bouncy', 'Brilliant', 'Balding', 'Budding', 'Busy', 'Beautiful', 'Body-builder', 'Bad'],
    'C': ['Cheerful', 'Creative', 'Curious', 'Clever', 'Caring', 'Charming', 'Comic genius', 'Cooperative', 'Colorful', 'Courageous', 'Cake-eating'],
    'D': ['Daring', 'Delightful', 'Dynamic', 'Dazzling', 'Dimpled', 'Dreamy', 'Determined', 'Dandy', 'Dexter-vibes', 'Dependable', 'Darling', 'Dark'],
    'E': ['Energetic', 'Enthusiastic', 'Exciting', 'Expressive', 'Easygoing', 'Empathetic', 'Enjoyable', 'Endearing', 'Excellent', 'Eager', 'Evil genius'],
    'F': ['Friendly', 'Funny', 'Fearless', 'Fascinating', 'Fancy', 'Fantastic', 'Fierce', 'Flexible', 'Flourishing', 'Frolicking', 'Fabulous', 'Free-spirited'],
    'G': ['Generous', 'Gentle', 'Giggly', 'Glorious', 'Grateful', 'Graceful', 'Gregarious', 'Growing', 'Gleeful', 'Genuine', 'Gentle giant'],
    'H': ['Happy', 'Hopeful', 'Humorous', 'Harmonious', 'Heartwarming', 'Helpful', 'High-spirited', 'Honest', 'Hardworking', 'Humble', 'Homesick', 'Hard-to-reach', 'Handsome'],
    'I': ['Imaginative', 'Inspiring', 'Inventive', 'Inquisitive', 'Impressive', 'Interesting', 'Iconic', 'Intelligent', 'Ingenious', 'Innocent', 'Icy', 'Impatient'],
    'J': ['Joyful', 'Juicy', 'Jiggly', 'Jellybean-loving', 'Jolly', 'Jazzy', 'Jumpy', 'Jet-setter', 'Jaw-dropping', 'Jealous', 'Judgemental', 'Joker', 'Junk-collecting'],
    'K': ['Kind', 'Know-it-all', 'Knowledgeable', 'Kaleidoscopic', 'Kooky', 'Kickboxing', 'Kale-loving', 'Knife-wielding', 'Knight', 'Kind'],
    'L': ['Lively', 'Lovable', 'Legendary', 'Lucky', 'Luminous', 'Loyal', 'Laughing', 'Laid-back', 'Loving', 'Limitless', 'Lyrical', 'Lost'],
    'M': ['Magical', 'Merry', 'Motivated', 'Magnificent', 'Mindful', 'Mischievous', 'Magnetic', 'Modest', 'Music-loving', 'Marvelous', 'Mad', 'Model-material'],
    'N': ['Nice', 'Nurturing', 'Nonchalant', 'Neat', 'Nifty', 'Noble', 'Neighborly', 'Nauseous', 'Nocturnal', 'Nature-loving', 'Neat-freak', 'Negative'],
    'O': ['Optimistic', 'Outgoing', 'Original', 'Open-minded', 'Observant', 'Orderly', 'Overjoyed', 'Offended', 'Outstanding', 'Open-hearted', 'Odd'],
    'P': ['Playful', 'Positive', 'Polite', 'Pleasant', 'Patient', 'Passionate', 'Peaceful', 'Practical', 'Perceptive', 'Proud', 'Panicked'],
    'Q': ['Quirky', 'Quick-witted', 'Quality-minded', 'Quiet', 'Quaint', 'Questioning', 'Quizzical', 'Qualified', 'Quizzical', 'Quick'],
    'R': ['Radiant', 'Resilient', 'Reliable', 'Respectful', 'Responsive', 'Romantic', 'Rambunctious', 'Rejoicing', 'Reverent', 'Radiant'],
    'S': ['Silly', 'Sincere', 'Sweet', 'Spirited', 'Supportive', 'Sunny', 'Smart', 'Serene', 'Strong', 'Smiling', 'Salty', 'Sarcastic'],
    'T': ['Talented', 'Thoughtful', 'Tolerant', 'Tenacious', 'Trustworthy', 'Thankful', 'Tender', 'Thriving', 'Tidy', 'Team-spirited', 'Tea-loving'],
    'U': ['Upbeat', 'Understanding', 'Unassuming', 'Unique', 'Uplifting', 'Unselfish', 'Unshakeable', 'Upstanding', 'Uplifted', 'Ubiquitous'],
    'V': ['Vibrant', 'Versatile', 'Vivacious', 'Valiant', 'Venturesome', 'Visionary', 'Vivifying', 'Virtuous', 'Validated', 'Vocal'],
    'W': ['Whimsical', 'Warm-hearted', 'Witty', 'Wise', 'Willing', 'Wondrous', 'Wacky', 'Winning', 'Welcoming', 'Wholesome', 'Wandering'],
    'X': ['Xtraordinary', 'Xcellent', 'Xuberant', 'Xciting', 'Xemplary', 'Xhilirating', 'Xhilarious', 'Xtra', 'Xotic', 'Xtraordinary'],
    'Y': ['Youthful', 'Yummy', 'Yearning', 'Yielded', 'Yoga-loving', 'Yay', 'Yes-minded', 'Yippee', 'Yare', 'Yay'],
    'Z': ['Zesty', 'Zany', 'Zealous', 'Zingy', 'Zestful', 'Zippy', 'Zigzagging', 'Zoological', 'Zany', 'Zen'],
  };

  export default adjectives;